# Generated by Django 4.2.28 on 2026-02-11 03:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector_name', models.CharField(max_length=200)),
                ('collector_email', models.EmailField(max_length=254)),
                ('collector_phone', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
